### ISSUE TITLE
No longer working with 2.4

### ISSUE THREAD

**Issue by DigiAngel** [initconf/smtp-analysis#1]
Topic says it..after upgrading I get:

error in /usr/local/bro/share/bro/site/./smtp-embedded-url-bloom.bro, line 40: value used but not set (bloomfilter_basic_init)

Any help with this?  And thank you...these are a staple for me.

**Comment by initconf** [comment]
This is now fixed! Please checkout smtp-embedded-url-bloom.bro again!
